spring.application.name=Recintos-Backend
server.port=8080
security.basic.enable: false
security.ignored=/**

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql:
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:rambi}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
